# Generated by Django 5.1.3 on 2024-11-29 09:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_patient_income'),
        ('wards', '0004_ward_daily_bed_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accountant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('contact', models.CharField(max_length=15)),
                ('shift_timings', models.CharField(choices=[('12:00 PM - 8:00 AM', '12:00 PM - 8:00 AM'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('4:00 PM - 12:00 PM', '4:00 PM - 12:00 PM')], default='12:00 PM - 8:00 AM', max_length=30)),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='accountant_profile', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountants', to='wards.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('bed_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('surgery_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('medicine_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('lab_test_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='patients.patient')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_generated_on', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], default='unpaid', max_length=10)),
                ('paid_on', models.DateTimeField(blank=True, null=True)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('accountant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hospital_bills', to='billing.accountant')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_bills', to='patients.patient')),
            ],
        ),
    ]
