# Generated by Django 5.1.3 on 2024-12-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
    ]
