# Generated by Django 5.1.3 on 2024-12-10 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_billing_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalbill',
            name='bill_generated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
