# Generated by Django 5.1.3 on 2024-12-12 05:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_hospitalbill_bill_generated_on'),
        ('patients', '0004_alter_patient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospitalbill',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_bills', to='patients.patient'),
        ),
    ]
