# Generated by Django 5.1.3 on 2024-11-29 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_alter_doctor_blood'),
        ('medical_records', '0002_medicalrecord_diagnoses_medicalrecord_treatment_plan'),
        ('patients', '0002_patient_income'),
        ('wards', '0004_ward_daily_bed_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalrecord',
            name='blood_group',
            field=models.CharField(blank=True, choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('ABO', 'Blood type unknown or not specified')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='discharge_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='emergency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='ward_admit_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='ward_admitted_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admitted_ward', to='wards.ward'),
        ),
        migrations.CreateModel(
            name='Surgery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surgery_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('surgery_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surgeon_name', to='doctors.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgeries', to='patients.patient')),
            ],
        ),
        migrations.AddField(
            model_name='medicalrecord',
            name='surgeries',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surgeries_performed', to='medical_records.surgery'),
        ),
    ]
