# Generated by Django 5.1.3 on 2024-12-09 05:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0003_medicalrecord_blood_group_and_more'),
        ('patients', '0004_alter_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='labprescription',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lab_prescriptions', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medicine_prescriptions', to='patients.patient'),
        ),
    ]
