# Generated by Django 5.1.3 on 2024-12-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0004_labprescription_patient_medicineprescription_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='labprescription',
            name='test_instructions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='medicineprescription',
            name='instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
