# Generated by Django 5.1.3 on 2024-12-11 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0003_labtestallocation'),
        ('medical_records', '0006_alter_medicalrecord_patient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labprescription',
            name='test_name',
        ),
        migrations.AddField(
            model_name='labprescription',
            name='test',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='laboratory.test'),
        ),
    ]
