# Generated by Django 5.1.3 on 2024-12-11 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0007_remove_labprescription_test_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labprescription',
            name='instructions',
        ),
    ]
