# Generated by Django 5.1.3 on 2024-11-29 10:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wards', '0004_ward_daily_bed_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityGuard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('contact', models.CharField(max_length=15)),
                ('shift_timings', models.CharField(choices=[('12:00 PM - 8:00 AM', '12:00 PM - 8:00 AM'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('4:00 PM - 12:00 PM', '4:00 PM - 12:00 PM')], default='12:00 PM - 8:00 AM', max_length=30)),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_guard_profile', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_guards', to='wards.ward')),
            ],
        ),
        migrations.CreateModel(
            name='Sweeper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('contact', models.CharField(max_length=15)),
                ('shift_timings', models.CharField(choices=[('12:00 PM - 8:00 AM', '12:00 PM - 8:00 AM'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('4:00 PM - 12:00 PM', '4:00 PM - 12:00 PM')], default='12:00 PM - 8:00 AM', max_length=30)),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sweeper_profile', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sweepers', to='wards.ward')),
            ],
        ),
    ]
