# Generated by Django 5.1.3 on 2024-12-02 10:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact_number', models.CharField(max_length=15, unique=True)),
                ('shift', models.CharField(blank=True, choices=[('12:00 AM - 8:00 AM', '12:00 AM - 8:00 AM'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('4:00 PM - 12:00 AM', '4:00 PM - 12:00 AM'), ('SPARE', 'Spare')], max_length=20)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receptionist_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
