# Generated by Django 5.1.3 on 2024-12-02 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_receptionist_age_receptionist_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receptionist',
            name='email',
        ),
    ]
