# Generated by Django 5.1.3 on 2024-12-12 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_remove_receptionist_email'),
        ('wards', '0006_alter_ward_daily_bed_fee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Nurse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('blood', models.CharField(blank=True, choices=[('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative'), ('O+', 'O Positive'), ('O-', 'O Negative'), ('ABO', 'Blood type unknown or not specified')], default='ABO', max_length=10)),
                ('specialization', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=15)),
                ('experience', models.IntegerField()),
                ('shift_timings', models.CharField(choices=[('12:00 PM - 8:00 AM', '12:00 PM - 8:00 AM'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('4:00 PM - 12:00 PM', '4:00 PM - 12:00 PM')], default='12:00 PM - 8:00 AM', max_length=30)),
                ('is_available', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_profile', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nurses', to='wards.ward')),
            ],
        ),
    ]
