# Generated by Django 5.1.3 on 2024-12-12 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_nurse'),
        ('wards', '0006_alter_ward_daily_bed_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securityguard',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='security_guards', to='wards.ward'),
        ),
        migrations.AlterField(
            model_name='sweeper',
            name='ward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sweepers', to='wards.ward'),
        ),
    ]
