# Generated by Django 5.1.3 on 2024-12-10 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_doctorfeedback_servicefeedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorfeedback',
            old_name='content',
            new_name='reviews',
        ),
        migrations.RenameField(
            model_name='servicefeedback',
            old_name='content',
            new_name='reviews',
        ),
    ]
