# Generated by Django 5.1.3 on 2024-11-27 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='name',
            new_name='medicine_name',
        ),
    ]
