# Generated by Django 5.1.3 on 2024-12-09 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_alter_patient_user'),
        ('pharmacy', '0002_rename_name_medicine_medicine_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicineAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('allocated_at', models.DateTimeField(auto_now_add=True)),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='pharmacy.medicine')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='patients.patient')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='pharmacy.pharmacy')),
            ],
        ),
    ]
