# Generated by Django 5.1.3 on 2024-12-11 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0003_medicineallocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicineallocation',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
