# Generated by Django 5.1.3 on 2024-11-28 06:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward_type', models.CharField(choices=[('ICU', 'Intensive Care Unit'), ('General', 'General Ward'), ('Maternity', 'Maternity Ward'), ('Pediatric', 'Pediatric Ward'), ('Orthopedic', 'Orthopedic Ward'), ('Cardiology', 'Cardiology Ward'), ('Neurology', 'Neurology Ward'), ('Surgical', 'Surgical Ward'), ('Psychiatric', 'Psychiatric Ward'), ('Emergency', 'Emergency Ward'), ('Burns', 'Burns Ward'), ('Isolation', 'Isolation Ward'), ('Rehabilitation', 'Rehabilitation Ward'), ('Geriatrics', 'Geriatrics Ward'), ('Oncology', 'Oncology Ward'), ('Urology', 'Urology Ward'), ('Nephrology', 'Nephrology Ward'), ('Plastic', 'Plastic Surgery Ward'), ('ENT', 'Ear, Nose, and Throat Ward'), ('Respiratory', 'Respiratory Ward'), ('Trauma', 'Trauma Ward'), ('Dialysis', 'Dialysis Ward'), ('Intensive', 'Intensive Care Ward')], max_length=100, unique=True)),
                ('capacity', models.PositiveIntegerField(default=40)),
            ],
        ),
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('occupied', 'Occupied'), ('free', 'Free'), ('cleaning', 'Cleaning'), ('maintenance', 'Maintenance')], default='free', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beds', to='wards.ward')),
            ],
        ),
        migrations.CreateModel(
            name='WardManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift', models.CharField(choices=[('00:00-08:00', '12:00 AM - 8:00 AM'), ('08:00-16:00', '8:00 AM - 4:00 PM'), ('16:00-00:00', '4:00 PM - 12:00 AM')], max_length=11)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ward_manager', to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='wards.ward')),
            ],
        ),
    ]
