# Generated by Django 5.1.3 on 2024-11-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='ward_type',
            field=models.CharField(choices=[('ICU', 'Intensive Care Unit'), ('General', 'General Ward'), ('Maternity', 'Maternity Ward')], max_length=100, unique=True),
        ),
    ]
