# Generated by Django 5.1.3 on 2024-11-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0002_alter_ward_ward_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='ward_type',
            field=models.CharField(choices=[('ICU', 'Intensive Care Unit'), ('General', 'General Ward'), ('Maternity', 'Maternity Ward'), ('Pediatric', 'Pediatric Ward'), ('Orthopedic', 'Orthopedic Ward'), ('Cardiology', 'Cardiology Ward'), ('Neurology', 'Neurology Ward'), ('Surgical', 'Surgical Ward'), ('Psychiatric', 'Psychiatric Ward'), ('Emergency', 'Emergency Ward'), ('Burns', 'Burns Ward'), ('Isolation', 'Isolation Ward'), ('Rehabilitation', 'Rehabilitation Ward'), ('Geriatrics', 'Geriatrics Ward'), ('Oncology', 'Oncology Ward'), ('Urology', 'Urology Ward'), ('Nephrology', 'Nephrology Ward'), ('Plastic', 'Plastic Surgery Ward'), ('ENT', 'Ear, Nose, and Throat Ward'), ('Respiratory', 'Respiratory Ward'), ('Trauma', 'Trauma Ward'), ('Dialysis', 'Dialysis Ward'), ('Intensive', 'Intensive Care Ward')], max_length=100, unique=True),
        ),
    ]
