# Generated by Django 5.1.3 on 2024-11-29 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0003_alter_ward_ward_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='ward',
            name='daily_bed_fee',
            field=models.PositiveIntegerField(default=100),
        ),
    ]
