# Generated by Django 5.1.3 on 2024-12-11 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wards', '0005_alter_wardmanager_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ward',
            name='daily_bed_fee',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
        ),
    ]
