# Generated by Django 5.1.3 on 2024-11-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_doctor_is_available_doctor_shift_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='shift_end_time',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='shift_start_time',
        ),
        migrations.AddField(
            model_name='doctor',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='doctor',
            name='blood',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='doctor',
            name='shift_timings',
            field=models.CharField(choices=[('12:00 PM - 8:00 AM', '12:00 PM - 8:00 AM'), ('8:00 AM - 4:00 PM', '8:00 AM - 4:00 PM'), ('4:00 PM - 12:00 PM', '4:00 PM - 12:00 PM')], default='12:00 PM - 8:00 AM', max_length=30),
        ),
    ]
