# Generated by Django 5.1.3 on 2024-12-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0005_remove_doctor_department_doctor_ward'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.IntegerField(default=200),
        ),
    ]
